### ISSUE TITLE
Meta-issue: TODOs for the relaunch

### ISSUE THREAD

**Issue by beta-ziliani** [crystal-lang/crystal-website#423]
* Post
   - [ ] Add discourse plugin
   - [ ] Figure out order of author displayed in the list
   - [ ] Add latest release box to the main page
 * Sponsors
   - [ ] Clean, improve FAQ text, and make it collapsible?
   - [ ] Add Manas
   - [x] Mark enterprise sponsors properly (current it's just the top 3)
   - [ ] Paginate list of sponsors or collapse inactive ones?

**Comment by straight-shoota** [comment]
Related to Discourse plugin: #240

**Comment by straight-shoota** [comment]
Resolved by #614
